function makeXlsx(rows,sheetName='Sheet1'){const files=[{name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'},{name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},{name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xmlEsc(sheetName)}" sheetId="1" r:id="rId1"/></sheets></workbook>`},{name:'xl/_rels/workbook.xml.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'},{name:'xl/styles.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'},{name:'xl/worksheets/sheet1.xml',data:makeSheet(rows)}];return zipStore(files)}
function safeName(s){return String(s||'customer').replace(/[\/:*?"<>|]+/g,'-').replace(/\s+/g,'_').slice(0,50)}
function isAndroidNative(){return !!(window.AndroidApp&&typeof window.AndroidApp.shareFile==='function'&&typeof window.AndroidApp.saveFile==='function')}
async function blobToBase64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let binary='',step=0x8000;for(let i=0;i<bytes.length;i+=step){binary+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(i+step,bytes.length)))}return btoa(binary)}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1800)}
async function saveBlob(blob,name){if(isAndroidNative()){try{const b64=await blobToBase64(blob);window.AndroidApp.saveFile(b64,name,blob.type||'application/octet-stream');return true}catch(e){console.error(e);toast('ذخیره فایل انجام نشد');return false}}downloadBlob(blob,name);return true}
async function shareBlobNative(blob,name,title,text){if(!isAndroidNative())return false;try{const b64=await blobToBase64(blob);window.AndroidApp.shareFile(b64,name,blob.type||'application/octet-stream',title||'',text||'');return true}catch(e){console.error(e);toast('ارسال فایل انجام نشد');return false}}
window.onNativeMessage=function(type,message){toast(message||'انجام شد')};
window.handleAndroidBack=function(){const open=[...document.querySelectorAll('.overlay.open')].pop();if(open){if(open.id!=='successOverlay')closeOverlay(open.id);else closeOverlay('successOverlay');return true}if(!$('historyScreen').hidden){showCatalog();return true}return false};
function orderRows(o){const rows=[['رادیان پارت آریا','سفارش مشتری'],['شماره سفارش',o.id],['نسخه اپ',o.appVersion||APP_VERSION],['نسخه لیست قیمت',o.catalogVersion||''],['تاریخ انتشار لیست',o.releaseDate||RELEASE_DATE_FA],['مشتری',o.customer],['تلفن',o.phone],['شهر',o.city],['تاریخ سفارش شمسی',o.orderDatePersian],['سررسید ۱۲۰ روزه شمسی',o.duePersian],['توضیحات',o.notes],[],['ردیف','کد کالا','نام کالا','گروه','تعداد در کارتن','واحد','تعداد سفارش','قیمت واحد (ریال)','جمع (ریال)']];o.items.forEach(x=>rows.push([x.seq,x.code||'',x.name,x.group,x.packQty==null?'':x.packQty,x.unit||'',x.qty,x.price,x.total]));rows.push([],['جمع کل','','','','','','','',o.total]);return rows}
function catalogRows(list){return [['ردیف','کد کالا','نام کالا','گروه','تعداد در کارتن','واحد','قیمت (ریال)','وضعیت قیمت'],...list.map(p=>[p.seq,p.code||'',p.name,p.group,p.packQty==null?'':p.packQty,p.unit||'',p.price==null?'':p.price,p.price==null?'قیمت نامشخص':'دارای قیمت']),[],['نسخه اپ',APP_VERSION],['تاریخ انتشار لیست',catalogMeta.releaseDateFa||RELEASE_DATE_FA],['تعداد کالا',list.length]]}
async function downloadOrderXlsx(o){const ok=await saveBlob(makeXlsx(orderRows(o),'سفارش'),`RadianPart_Order_${safeName(o.customer)}_${o.orderDate}.xlsx`);if(ok&&!isAndroidNative())toast('فایل Excel سفارش دانلود شد')}
async function exportCatalog(all=true){const list=all?PRODUCTS:filteredProducts(),ok=await saveBlob(makeXlsx(catalogRows(list),all?'لیست کالاها':'نتایج جستجو'),`RadianPart_Catalog_${all?'Full':'Filtered'}_v${APP_VERSION}.xlsx`);if(ok&&!isAndroidNative())toast('فایل Excel لیست کالا دانلود شد')}
async function shareOrderObject(o){const blob=makeXlsx(orderRows(o),'سفارش'),name=`RadianPart_Order_${safeName(o.customer)}_${o.orderDate}.xlsx`,title='سفارش رادیان پارت آریا',text=`سفارش ${o.customer} - ${o.id}`;if(await shareBlobNative(blob,name,title,text))return;try{const file=new File([blob],name,{type:blob.type});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title,text,files:[file]});return}downloadBlob(blob,name);alert('ارسال مستقیم فایل در این مرورگر پشتیبانی نمی‌شود. فایل Excel دانلود شد تا از واتساپ، تلگرام یا ایمیل ارسال کنید.')}catch(e){if(e?.name!=='AbortError'){downloadBlob(blob,name);alert('ارسال مستقیم انجام نشد؛ فایل Excel دانلود شد.')}}}
function init(){loadCachedCatalog();ordersCache=readOrdersFromStorage();renderChips();loadState();$('orderDate').value=localISODate();calcDue();renderProducts();renderCart();renderHistory();updateCatalogStatus();setTimeout(()=>{checkCatalogUpdate(false);checkAppUpdate()},900)}
$('enterApp').addEventListener('click',()=>{$('welcomeScreen').classList.add('hidden');setTimeout(()=>$('search').focus(),220)});$('updateCatalog').addEventListener('click',()=>checkCatalogUpdate(true));$('downloadAppUpdate').addEventListener('click',()=>{if(pendingAppUpdate)openExternal(pendingAppUpdate.apkUrl)});$('laterAppUpdate').addEventListener('click',()=>closeOverlay('appUpdateOverlay'));
$('search').addEventListener('input',renderProducts);$('clearSearch').addEventListener('click',()=>{$('search').value='';renderProducts();$('search').focus()});$('qtyPlus').addEventListener('click',()=>{$('qtyInput').value=clampQty(Number($('qtyInput').value)+1)});$('qtyMinus').addEventListener('click',()=>{$('qtyInput').value=clampQty(Number($('qtyInput').value)-1)});$('qtyInput').addEventListener('change',()=>{$('qtyInput').value=clampQty($('qtyInput').value)});$('confirmAdd').addEventListener('click',confirmAdd);$('qtyInput').addEventListener('keydown',e=>{if(e.key==='Enter')confirmAdd()});
$('openCart').addEventListener('click',()=>{renderCart();openOverlay('cartOverlay')});$('goCheckout').addEventListener('click',()=>{if(!cartStats().items)return;closeOverlay('cartOverlay');setAutomaticOrderDate();calcDue();renderCheckoutSummary();openOverlay('checkoutOverlay')});$('backToCart').addEventListener('click',()=>{closeOverlay('checkoutOverlay');openOverlay('cartOverlay')});$('clearCart').addEventListener('click',()=>{if(confirm('همه کالاهای سبد پاک شوند؟')){cart={};persistState();renderCart();renderProducts();closeOverlay('cartOverlay');toast('سبد پاک شد')}});$('saveOrder').addEventListener('click',saveOrder);['customer','phone','city','notes'].forEach(id=>$(id).addEventListener('input',persistState));
$('shareSaved').addEventListener('click',()=>{if(lastSavedOrder)shareOrderObject(lastSavedOrder)});$('excelSaved').addEventListener('click',()=>{if(lastSavedOrder)downloadOrderXlsx(lastSavedOrder)});$('newOrder').addEventListener('click',startNewOrder);$('closeSuccess').addEventListener('click',()=>closeOverlay('successOverlay'));
$('exportCatalog').addEventListener('click',()=>exportCatalog(true));$('exportFiltered').addEventListener('click',()=>exportCatalog(false));$('showTools').addEventListener('click',()=>{const box=$('toolsBox');box.hidden=!box.hidden;if(!box.hidden)box.scrollIntoView({behavior:'smooth',block:'start'})});$('hideTools').addEventListener('click',()=>{$('toolsBox').hidden=true});$('showHistory').addEventListener('click',showHistoryScreen);$('viewSavedOrders').addEventListener('click',()=>{closeOverlay('successOverlay');showHistoryScreen()});document.querySelectorAll('[data-back-catalog]').forEach(b=>b.addEventListener('click',showCatalog));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeOverlay(b.dataset.close)));document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o&&o.id!=='successOverlay')closeOverlay(o.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){const o=[...document.querySelectorAll('.overlay.open')].pop();if(o&&o.id!=='successOverlay')closeOverlay(o.id)}});
init();