let PRODUCTS=EMBEDDED_PRODUCTS.map(p=>({...p})), catalogMeta={catalogVersion:EMBEDDED_CATALOG_VERSION,releaseDateFa:RELEASE_DATE_FA,releaseDateG:RELEASE_DATE_G,source:"embedded"};
let cart={}, selectedGroup='', selectedProduct=null, lastSavedOrder=null, editingOrderId=null, pendingAppUpdate=null, ordersCache=[];
const $=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat('fa-IR').format(Number(n)||0), money=n=>fmt(n)+' ریال';
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function xmlEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function localISODate(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function parseDateOnly(v){if(!v)return null;const [y,m,d]=v.split('-').map(Number);if(!y||!m||!d)return null;return new Date(y,m-1,d,12,0,0,0)}
function toPersianDate(d){if(!d||isNaN(d))return '—';return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function dueFrom(v){const base=parseDateOnly(v);if(!base)return null;const due=new Date(base);due.setDate(due.getDate()+120);return due}
function calcDue(){const base=parseDateOnly($('orderDate').value),due=dueFrom($('orderDate').value);$('orderDatePersian').value=base?toPersianDate(base):'—';$('duePersian').textContent=due?toPersianDate(due):'—'}
function setAutomaticOrderDate(){if(editingOrderId)return;$('orderDate').value=localISODate();calcDue()}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function openOverlay(id){$(id).classList.add('open');document.body.style.overflow='hidden'}
function closeOverlay(id){$(id).classList.remove('open');if(!document.querySelector('.overlay.open'))document.body.style.overflow=''}
function productKey(p){return String((p&&p.code)||('seq:'+((p&&p.seq)||'')))}
function findProduct(key){const k=String(key??'');return PRODUCTS.find(p=>productKey(p)===k)||PRODUCTS.find(p=>String(p.seq)===k||('seq:'+p.seq)===k)}
function normalizeRemoteProduct(p,index){const price=(p.price===null||p.price===undefined||p.price==='')?null:Number(p.price),pack=(p.packQty===null||p.packQty===undefined||p.packQty==='')?null:Number(p.packQty);return {row:Number(p.row)||0,seq:Number(p.seq)||index+1,name:String(p.name||'').trim(),code:String(p.code||'').trim(),price:Number.isFinite(price)?price:null,group:String(p.group||'سایر').trim()||'سایر',packQty:Number.isFinite(pack)?pack:null,unit:String(p.unit||'').trim()}}
function validCatalogProducts(list){return Array.isArray(list)&&list.length>0&&list.every(p=>p&&String(p.name||'').trim()&&(String(p.code||'').trim()||Number(p.seq)>0))}
function migrateCartKeys(raw){const out={};Object.entries(raw||{}).forEach(([k,v])=>{const qty=Number(v)||0;if(qty<=0)return;const p=findProduct(k);if(p)out[productKey(p)]=(out[productKey(p)]||0)+qty});return out}
function loadCachedCatalog(){try{const raw=localStorage.getItem('rpa_catalog_cache_v1'),metaRaw=localStorage.getItem('rpa_catalog_meta_v1');if(!raw)return false;const data=JSON.parse(raw),list=Array.isArray(data)?data:data.products;if(!validCatalogProducts(list))return false;PRODUCTS=list.map(normalizeRemoteProduct);catalogMeta={...(metaRaw?JSON.parse(metaRaw):{}),...(Array.isArray(data)?{}:data),source:'cache'};return true}catch(e){return false}}
function saveCatalogCache(payload){try{localStorage.setItem('rpa_catalog_cache_v1',JSON.stringify(payload));localStorage.setItem('rpa_catalog_meta_v1',JSON.stringify({catalogVersion:payload.catalogVersion||'',releaseDateFa:payload.releaseDateFa||'',releaseDateG:payload.releaseDateG||'',publishedAt:payload.publishedAt||'',source:'cache'}))}catch(e){}}
function updateCatalogStatus(){if(!$('catalogVersionLabel'))return;$('catalogVersionLabel').textContent=catalogMeta.catalogVersion||'نسخه داخلی';$('catalogDateLabel').textContent=catalogMeta.releaseDateFa||RELEASE_DATE_FA;$('catalogSourceLabel').textContent=catalogMeta.source==='remote'?'بروزرسانی آنلاین':catalogMeta.source==='cache'?'آخرین نسخه ذخیره‌شده':'نسخه همراه برنامه'}
function compareVersion(a,b){const A=String(a||'0').split('.').map(x=>parseInt(x,10)||0),B=String(b||'0').split('.').map(x=>parseInt(x,10)||0);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x>y)return 1;if(x<y)return -1}return 0}
async function fetchJson(url,timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
async function checkCatalogUpdate(manual=false){const btn=$('updateCatalog');if(btn){btn.disabled=true;btn.textContent='در حال بررسی...'}try{const ver=await fetchJson(UPDATE_BASE_URL+'/catalog-version.json');const remoteVersion=String(ver.catalogVersion||'');if(!remoteVersion)throw new Error('invalid catalog version');if(remoteVersion===String(catalogMeta.catalogVersion||'')){if(manual)toast('لیست قیمت شما به‌روز است');return false}const url=ver.catalogUrl?(ver.catalogUrl.startsWith('http')?ver.catalogUrl:UPDATE_BASE_URL+'/'+ver.catalogUrl.replace(/^\//,'')):UPDATE_BASE_URL+'/catalog.json';const data=await fetchJson(url,12000),list=Array.isArray(data)?data:data.products;if(!validCatalogProducts(list))throw new Error('invalid catalog');PRODUCTS=list.map(normalizeRemoteProduct);catalogMeta={...(Array.isArray(data)?{}:data),...ver,catalogVersion:remoteVersion,source:'remote'};saveCatalogCache({...catalogMeta,products:PRODUCTS});cart=migrateCartKeys(cart);persistState();selectedGroup='';renderChips();renderProducts();renderCart();updateCatalogStatus();toast('لیست قیمت جدید دریافت شد');return true}catch(e){if(manual)toast('اینترنت یا فایل بروزرسانی در دسترس نیست');return false}finally{if(btn){btn.disabled=false;btn.textContent='بروزرسانی لیست قیمت'}}}
function showAppUpdate(info){if(!info||!info.apkUrl||compareVersion(info.latestVersion,APP_VERSION)<=0)return;pendingAppUpdate=info;$('appUpdateVersion').textContent='نسخه '+String(info.latestVersion);$('appUpdateMessage').textContent=info.message||'نسخه جدید رادیان پارت آریا آماده نصب است.';$('laterAppUpdate').style.display=info.mandatory?'none':'';openOverlay('appUpdateOverlay')}
async function checkAppUpdate(){try{const info=await fetchJson(UPDATE_BASE_URL+'/app-version.json');showAppUpdate(info)}catch(e){}}
function openExternal(url){if(!url)return;if(window.AndroidApp&&typeof window.AndroidApp.openUrl==='function'){window.AndroidApp.openUrl(url);return}window.open(url,'_blank')}
function loadState(){try{cart=JSON.parse(localStorage.getItem('rpa_customer_cart')||'{}')||{};const f=JSON.parse(localStorage.getItem('rpa_customer_form')||'{}')||{};['customer','phone','city','notes'].forEach(k=>{if(f[k])$(k).value=f[k]})}catch(e){cart={}}cart=migrateCartKeys(cart)}
function persistState(){try{localStorage.setItem('rpa_customer_cart',JSON.stringify(cart));localStorage.setItem('rpa_customer_form',JSON.stringify({customer:$('customer').value,phone:$('phone').value,city:$('city').value,notes:$('notes').value}))}catch(e){}}
function groups(){return [...new Set(PRODUCTS.map(p=>p.group))]}
function renderChips(){const all=[{v:'',t:'همه'},...groups().map(g=>({v:g,t:g}))];$('chips').innerHTML=all.map(x=>`<button class="chip ${selectedGroup===x.v?'active':''}" data-group="${escapeHtml(x.v)}">${escapeHtml(x.t)}</button>`).join('');document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{selectedGroup=b.dataset.group;renderChips();renderProducts()}))}
function normalizeSearchText(value){return String(value??'').toLowerCase().replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/ة/g,'ه').replace(/[أإٱ]/g,'ا').replace(/ؤ/g,'و').replace(/ئ/g,'ی').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[\u200c\u200d\ufeff]/g,' ').replace(/([0-9])([a-z\u0600-\u06ff])/gi,'$1 $2').replace(/([a-z\u0600-\u06ff])([0-9])/gi,'$1 $2').replace(/[^0-9a-z\u0600-\u06ff]+/gi,' ').replace(/\s+/g,' ').trim()}
function searchWords(value){return normalizeSearchText(value).split(' ').filter(Boolean)}
function productSearchData(p){const name=normalizeSearchText(p.name),code=normalizeSearchText(p.code||''),group=normalizeSearchText(p.group||''),unit=normalizeSearchText(p.unit||'');return {name,code,group,unit,all:`${name} ${code} ${group} ${unit}`.trim(),nameWords:name.split(' ').filter(Boolean),groupWords:group.split(' ').filter(Boolean)}}
function productSearchScore(p,query){const q=normalizeSearchText(query);if(!q)return 1;const parts=searchWords(q),d=productSearchData(p);if(!parts.every(t=>d.all.includes(t)))return -1;let score=0;const compact=q.replace(/\s/g,'');if(d.code&&compact===d.code.replace(/\s/g,''))score+=10000;else if(d.code&&d.code.replace(/\s/g,'').startsWith(compact)&&/^\d+$/.test(compact))score+=7000;if(d.name===q)score+=6000;else if(d.name.includes(q))score+=4000;if(d.group===q)score+=1500;for(const t of parts){if(d.code===t)score+=1200;else if(d.code.startsWith(t))score+=800;else if(d.code.includes(t))score+=550;if(d.nameWords.includes(t))score+=500;else if(d.nameWords.some(w=>w.startsWith(t)))score+=350;else if(d.name.includes(t))score+=220;if(d.groupWords.includes(t))score+=260;else if(d.group.includes(t))score+=140;if(d.unit&&d.unit.includes(t))score+=60}return score}
function filteredProducts(){const q=$('search').value;return PRODUCTS.map((p,index)=>({p,index,score:productSearchScore(p,q)})).filter(x=>(!selectedGroup||x.p.group===selectedGroup)&&x.score>=0).sort((a,b)=>q.trim()?(b.score-a.score||a.index-b.index):a.index-b.index).map(x=>x.p)}
function renderProducts(){const list=filteredProducts();$('resultCount').textContent=fmt(list.length);$('activeFilter').textContent=selectedGroup||'همه گروه‌ها';$('clearSearch').style.display=$('search').value?'block':'none';$('products').innerHTML=list.length?list.map(p=>{const q=Number(cart[productKey(p)]||0),pack=p.packQty==null?'—':fmt(p.packQty),unit=p.unit||'—';return `<article class="product"><div class="product-main"><div class="product-info"><div class="pname">${escapeHtml(p.name)}</div><div class="pmeta"><span class="tag">${escapeHtml(p.group)}</span><span>کد: ${escapeHtml(p.code||'—')}</span></div><div class="packmeta"><span>تعداد در کارتن: <b>${escapeHtml(pack)}</b></span><span>واحد: <b>${escapeHtml(unit)}</b></span></div>${q?`<div class="in-cart">✓ ${fmt(q)} ${escapeHtml(p.unit||'عدد')} در سبد</div>`:''}</div></div><div class="product-bottom"><div class="price ${p.price==null?'missing':''}">${p.price==null?'قیمت نامشخص':money(p.price)}</div><button class="add-btn" data-add="${escapeHtml(productKey(p))}" ${p.price==null?'disabled':''}>${q?'افزودن بیشتر':'افزودن'}</button></div></article>`}).join(''):'<div class="empty">کالایی با این جستجو پیدا نشد.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>openQty(b.dataset.add)))}
function clampQty(v){const n=parseInt(v,10);return Math.min(99999,Math.max(1,Number.isFinite(n)?n:1))}
function openQty(key){const p=findProduct(key);if(!p||p.price==null)return;selectedProduct=p;$('qtyInput').value='1';$('qtyProduct').innerHTML=`<div class="title">${escapeHtml(p.name)}</div><div class="sub">کد: ${escapeHtml(p.code||'—')} · گروه: ${escapeHtml(p.group)} · تعداد در کارتن: ${p.packQty==null?'—':fmt(p.packQty)} · واحد: ${escapeHtml(p.unit||'—')}</div><div class="amount">${money(p.price)}</div>`;openOverlay('qtyOverlay');setTimeout(()=>{$('qtyInput').focus();$('qtyInput').select()},120)}
function confirmAdd(){if(!selectedProduct)return;const q=clampQty($('qtyInput').value);const key=productKey(selectedProduct);cart[key]=(Number(cart[key])||0)+q;persistState();renderProducts();renderCart();closeOverlay('qtyOverlay');toast(`${fmt(q)} عدد به سبد اضافه شد`)}
function cartEntries(){return Object.entries(cart).map(([key,qty])=>({key,p:findProduct(key),qty:Number(qty)})).filter(x=>x.p&&x.qty>0&&x.p.price!=null)}
function cartStats(){const e=cartEntries();return {entries:e,items:e.length,qty:e.reduce((s,x)=>s+x.qty,0),total:e.reduce((s,x)=>s+x.p.price*x.qty,0)}}