function renderCart(){const s=cartStats();$('cartDock').classList.toggle('show',s.items>0);$('dockItems').textContent=fmt(s.items);$('dockQty').textContent=fmt(s.qty);$('dockBadge').textContent=fmt(s.items);$('dockTotal').textContent=money(s.total);$('cartHeaderMeta').textContent=s.items?`${fmt(s.items)} قلم · ${fmt(s.qty)} تعداد سفارش`:'سبد خالی است';$('cartList').innerHTML=s.items?s.entries.map(({p,qty})=>{const pack=p.packQty==null||p.packQty===''?'ثبت نشده':fmt(p.packQty),unit=p.unit&&String(p.unit).trim()?p.unit:'ثبت نشده';return `<div class="cart-item"><div class="cart-title">${escapeHtml(p.name)}</div><div class="cart-meta">کد: ${escapeHtml(p.code||'—')} · قیمت واحد: ${money(p.price)}</div><div class="cart-specs"><div class="cart-spec">تعداد در کارتن: <b>${escapeHtml(pack)}</b></div><div class="cart-spec">واحد: <b>${escapeHtml(unit)}</b></div></div><div class="cart-controls"><button class="mini-btn" data-plus="${escapeHtml(productKey(p))}">+</button><input class="cart-qty" data-cartqty="${escapeHtml(productKey(p))}" type="number" inputmode="numeric" min="1" max="99999" value="${qty}"><button class="mini-btn" data-minus="${escapeHtml(productKey(p))}">−</button><button class="remove-btn" data-remove="${escapeHtml(productKey(p))}">حذف</button></div><div class="line-total">جمع این قلم: ${money(p.price*qty)}</div></div>`}).join(''):'<div class="empty">هنوز کالایی به سبد اضافه نکرده‌اید.</div>';$('cartSummary').innerHTML=`<div class="sumrow"><span>تعداد اقلام</span><strong>${fmt(s.items)}</strong></div><div class="sumrow"><span>تعداد کل سفارش</span><strong>${fmt(s.qty)}</strong></div><div class="sumrow total"><span>جمع سفارش</span><strong>${money(s.total)}</strong></div>`;$('goCheckout').disabled=!s.items;document.querySelectorAll('[data-plus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.plus,1)));document.querySelectorAll('[data-minus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.minus,-1)));document.querySelectorAll('[data-cartqty]').forEach(i=>i.addEventListener('change',()=>setQty(i.dataset.cartqty,i.value)));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeItem(b.dataset.remove)));renderCheckoutSummary()}
function changeQty(key,d){cart[key]=Math.max(1,(Number(cart[key])||1)+d);persistState();renderCart();renderProducts()}
function setQty(key,v){cart[key]=clampQty(v);persistState();renderCart();renderProducts()}
function removeItem(key){delete cart[key];persistState();renderCart();renderProducts();toast('کالا از سبد حذف شد')}
function renderCheckoutSummary(){const s=cartStats();$('checkoutSummary').innerHTML=`<div class="sumrow"><span>اقلام سفارش</span><strong>${fmt(s.items)} قلم / ${fmt(s.qty)} عدد</strong></div><div class="sumrow total"><span>جمع سفارش</span><strong>${money(s.total)}</strong></div>`}
function orderObject(){const s=cartStats(),v=$('orderDate').value||localISODate(),base=parseDateOnly(v),due=dueFrom(v),stamp=new Date(),existing=editingOrderId?getHistory().find(x=>x.id===editingOrderId):null,id=existing?.id||('RPA-'+v.replaceAll('-','')+'-'+String(stamp.getHours()).padStart(2,'0')+String(stamp.getMinutes()).padStart(2,'0')+String(stamp.getSeconds()).padStart(2,'0'));return {id,createdAt:existing?.createdAt||stamp.toISOString(),updatedAt:editingOrderId?stamp.toISOString():(existing?.updatedAt||''),customer:$('customer').value.trim(),phone:$('phone').value.trim(),city:$('city').value.trim(),orderDate:v,orderDatePersian:toPersianDate(base),dueDate:due?[due.getFullYear(),String(due.getMonth()+1).padStart(2,'0'),String(due.getDate()).padStart(2,'0')].join('-'):'',duePersian:toPersianDate(due),notes:$('notes').value.trim(),items:s.entries.map(({p,qty})=>({seq:p.seq,code:p.code,name:p.name,group:p.group,packQty:p.packQty,unit:p.unit||'',price:p.price,qty,total:p.price*qty})),total:s.total,appVersion:APP_VERSION,catalogVersion:catalogMeta.catalogVersion||'',releaseDate:catalogMeta.releaseDateFa||RELEASE_DATE_FA}}
function validateOrder(o){if(!o.items.length){toast('سبد سفارش خالی است');return false}if(!o.customer){$('customer').focus();toast('نام خود را وارد کنید');return false}return true}
function readOrdersFromStorage(){for(const key of ['rpa_orders_v22','rpa_orders']){try{const raw=localStorage.getItem(key);if(!raw)continue;const list=JSON.parse(raw);if(Array.isArray(list))return list}catch(e){}}return []}
function writeOrders(list){ordersCache=Array.isArray(list)?list:[];let ok=false;try{localStorage.setItem('rpa_orders_v22',JSON.stringify(ordersCache));localStorage.setItem('rpa_orders',JSON.stringify(ordersCache));ok=true}catch(e){}return ok}
function getHistory(){if(!Array.isArray(ordersCache)||!ordersCache.length)ordersCache=readOrdersFromStorage();return Array.isArray(ordersCache)?ordersCache:[]}
function updateHistoryCount(){const el=$('historyCount');if(el)el.textContent=fmt(getHistory().length)}
function saveOrder(){const wasEditing=!!editingOrderId,o=orderObject();if(!validateOrder(o))return;let list=getHistory().slice();if(wasEditing){const i=list.findIndex(x=>x.id===editingOrderId);if(i>=0)list[i]=o;else list.unshift(o)}else list.unshift(o);writeOrders(list);lastSavedOrder=o;editingOrderId=null;persistState();renderHistory();closeOverlay('checkoutOverlay');$('checkoutTitle').textContent='ثبت سفارش';$('checkoutModeMeta').textContent='اطلاعات را بررسی و سفارش را نهایی کنید';$('saveOrder').textContent='ثبت نهایی سفارش';$('successTitle').textContent=wasEditing?'تغییرات سفارش ذخیره شد':'سفارش ثبت شد';$('successOrderId').textContent=o.id;$('successSummary').textContent=`${fmt(o.items.length)} قلم · ${money(o.total)}`;openOverlay('successOverlay')}
function startNewOrder(){cart={};lastSavedOrder=null;editingOrderId=null;$('orderDate').value=localISODate();calcDue();$('checkoutTitle').textContent='ثبت سفارش';$('checkoutModeMeta').textContent='اطلاعات را بررسی و سفارش را نهایی کنید';$('saveOrder').textContent='ثبت نهایی سفارش';try{localStorage.removeItem('rpa_customer_cart')}catch(e){};renderCart();renderProducts();closeOverlay('successOverlay');window.scrollTo({top:0,behavior:'smooth'});toast('سفارش جدید آماده است')}
function editOrder(id){const o=getHistory().find(x=>x.id===id);if(!o)return;editingOrderId=id;cart={};(Array.isArray(o.items)?o.items:[]).forEach(x=>{const p=(x.code?PRODUCTS.find(y=>String(y.code)===String(x.code)):null)||PRODUCTS.find(y=>y.seq===Number(x.seq));if(p&&Number(x.qty)>0&&p.price!=null)cart[productKey(p)]=Number(x.qty)});$('customer').value=o.customer||'';$('phone').value=o.phone||'';$('city').value=o.city||'';$('notes').value=o.notes||'';$('orderDate').value=o.orderDate||localISODate();calcDue();$('checkoutTitle').textContent='ویرایش سفارش';$('checkoutModeMeta').textContent=`ویرایش سفارش ${o.id||''}`;$('saveOrder').textContent='ثبت تغییرات سفارش';persistState();showCatalog();renderProducts();renderCart();openOverlay('cartOverlay');toast('سفارش برای ویرایش بارگذاری شد')}
function showCatalog(){$('catalogScreen').hidden=false;$('historyScreen').hidden=true;window.scrollTo(0,0)}
function showHistoryScreen(){renderHistory();$('catalogScreen').hidden=true;$('historyScreen').hidden=false;window.scrollTo(0,0)}
function renderHistory(){const list=getHistory();updateHistoryCount();$('history').innerHTML=list.length?list.map(o=>{const items=Array.isArray(o.items)?o.items:[];return `<div class="history-item"><div class="history-head"><span>${escapeHtml(o.customer||'بدون نام')}</span><span>${money(Number(o.total)||0)}</span></div><div class="history-meta">${escapeHtml(o.orderDatePersian||o.orderDate||'—')} · سررسید ${escapeHtml(o.duePersian||o.dueDate||'—')}<br><span style="direction:ltr;display:inline-block">${escapeHtml(o.id||'—')}</span> · ${fmt(items.length)} قلم</div><details class="history-detail"><summary>مشاهده اقلام سفارش</summary><div class="history-products">${items.map(x=>`<div class="history-product"><div><strong>${escapeHtml(x.name||'')}</strong><br><small>کد: ${escapeHtml(x.code||'—')} · قیمت: ${money(Number(x.price)||0)}<br>تعداد در کارتن: ${escapeHtml(x.packQty==null||x.packQty===''?'ثبت نشده':fmt(x.packQty))} · واحد: ${escapeHtml(x.unit||'ثبت نشده')}</small></div><strong>${fmt(Number(x.qty)||0)} ${escapeHtml(x.unit||'')}</strong></div>`).join('')||'<div style="font-size:11px;color:#667085">جزئیات این سفارش موجود نیست.</div>'}</div></details><div class="history-actions"><button data-hedit="${escapeHtml(o.id||'')}">ویرایش</button><button data-hshare="${escapeHtml(o.id||'')}">ارسال مجدد</button><button data-hx="${escapeHtml(o.id||'')}">دانلود Excel</button></div></div>`}).join(''):'<div class="empty">هنوز سفارشی ثبت نشده است.<br><small>بعد از «ثبت نهایی سفارش»، سفارش در این قسمت نمایش داده می‌شود.</small></div>';document.querySelectorAll('[data-hedit]').forEach(b=>b.addEventListener('click',()=>editOrder(b.dataset.hedit)));document.querySelectorAll('[data-hx]').forEach(b=>b.addEventListener('click',()=>{const o=list.find(x=>x.id===b.dataset.hx);if(o)downloadOrderXlsx(o)}));document.querySelectorAll('[data-hshare]').forEach(b=>b.addEventListener('click',()=>{const o=list.find(x=>x.id===b.dataset.hshare);if(o)shareOrderObject(o)}))}
const crcTable=(()=>{let t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function le16(n){return new Uint8Array([n&255,(n>>>8)&255])}function le32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concat(arrs){const len=arrs.reduce((s,a)=>s+a.length,0),out=new Uint8Array(len);let p=0;for(const a of arrs){out.set(a,p);p+=a.length}return out}
function zipStore(files){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.data),crc=crc32(data),local=concat([le32(0x04034b50),le16(20),le16(0x0800),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),name,data]);locals.push(local);const central=concat([le32(0x02014b50),le16(20),le16(20),le16(0x0800),le16(0),le16(0),le16(0),le32(crc),le32(data.length),le32(data.length),le16(name.length),le16(0),le16(0),le16(0),le16(0),le32(0),le32(offset),name]);centrals.push(central);offset+=local.length}const csize=centrals.reduce((s,a)=>s+a.length,0),end=concat([le32(0x06054b50),le16(0),le16(0),le16(files.length),le16(files.length),le32(csize),le32(offset),le16(0)]);return new Blob([...locals,...centrals,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function colName(n){let s='';while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function makeSheet(rows){const data=rows.map((row,ri)=>`<row r="${ri+1}">`+row.map((v,ci)=>{if(v===null||v===undefined)return '';const r=colName(ci+1)+(ri+1),style=ri===0?' s="1"':'';if(typeof v==='number'&&Number.isFinite(v))return `<c r="${r}" t="n"${style}><v>${v}</v></c>`;return `<c r="${r}" t="inlineStr"${style}><is><t xml:space="preserve">${xmlEsc(v)}</t></is></c>`}).join('')+`</row>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><cols><col min="1" max="1" width="14" customWidth="1"/><col min="2" max="2" width="18" customWidth="1"/><col min="3" max="3" width="48" customWidth="1"/><col min="4" max="10" width="18" customWidth="1"/></cols><sheetData>${data}</sheetData></worksheet>`}