let radianInstallPrompt=null;
const byId=id=>document.getElementById(id);
function installed(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function isAndroid(){return /Android/i.test(navigator.userAgent)}
function isChrome(){return /Chrome\//i.test(navigator.userAgent)&&!/;\s*wv\)/i.test(navigator.userAgent)&&!/\bwv\b/i.test(navigator.userAgent)&&!/Rubika/i.test(navigator.userAgent)}
function isInAppBrowser(){const u=navigator.userAgent;return isAndroid()&&(/;\s*wv\)/i.test(u)||/\bwv\b/i.test(u)||/Rubika/i.test(u))}
function installLabels(){['installPwa','installWelcome','drawerInstall'].forEach(id=>{const b=byId(id);if(!b)return;b.textContent=installed()?'برنامه نصب شده است':'نصب برنامه روی گوشی';b.disabled=installed()})}
function currentChromeIntent(){const fallback=encodeURIComponent(location.href);const hostPath=location.host+location.pathname+location.search;return `intent://${hostPath}#Intent;scheme=https;package=com.android.chrome;S.browser_fallback_url=${fallback};end`}
function openInChrome(){location.href=currentChromeIntent()}
function closeInstallPanel(){byId('radianInstallPanel')?.classList.remove('open')}
function showInstallPanel(){let p=byId('radianInstallPanel');if(!p){p=document.createElement('div');p.id='radianInstallPanel';p.className='chrome-prompt';p.innerHTML=`<div class="chrome-card"><img src="logo.png?v=3404" alt="لوگوی رادیان"><h2>نصب رادیان روی گوشی</h2><p id="installPanelText"></p><button id="installPanelMain" class="chrome-open">شروع نصب</button><button id="installPanelClose" class="chrome-stay">بازگشت</button></div>`;document.body.appendChild(p);byId('installPanelClose').onclick=closeInstallPanel}const txt=byId('installPanelText'),main=byId('installPanelMain');if(installed()){txt.innerHTML='برنامه رادیان روی این گوشی نصب شده است.';main.textContent='برنامه نصب شده است';main.disabled=true}else if(isAndroid()&&!isChrome()){txt.innerHTML='برای اینکه نصب درست و سریع انجام شود، ابتدا این صفحه را در <b>Google Chrome</b> باز کنید.';main.textContent='باز کردن در Chrome';main.disabled=false;main.onclick=openInChrome}else if(radianInstallPrompt){txt.innerHTML='روی دکمه زیر بزنید؛ پنجره نصب خود اندروید باز می‌شود.';main.textContent='نصب برنامه';main.disabled=false;main.onclick=doNativeInstall}else{txt.innerHTML='اگر پنجره نصب هنوز آماده نشده، چند ثانیه صبر کنید. در Chrome می‌توانید از منوی سه‌نقطه نیز گزینه <b>Install app</b> یا <b>Add to Home screen</b> را انتخاب کنید.';main.textContent='بررسی مجدد نصب';main.disabled=false;main.onclick=()=>{if(radianInstallPrompt)doNativeInstall();else{setTimeout(()=>showInstallPanel(),350)}}}p.classList.add('open')}
async function doNativeInstall(){if(installed()){installLabels();closeInstallPanel();return}if(!radianInstallPrompt){showInstallPanel();return}const prompt=radianInstallPrompt;radianInstallPrompt=null;try{prompt.prompt();const choice=await prompt.userChoice;if(choice&&choice.outcome==='accepted'){closeInstallPanel()}}catch(e){}installLabels()}
async function installRadian(){if(installed()){installLabels();return}if(isAndroid()&&!isChrome()){showInstallPanel();return}if(radianInstallPrompt){await doNativeInstall();return}showInstallPanel()}
function welcome(){document.querySelectorAll('.overlay.open').forEach(x=>x.classList.remove('open'));const w=byId('welcomeScreen');if(w)w.classList.remove('hidden');document.body.style.overflow='';scrollTo(0,0)}
function addRuntimeStyles(){const s=document.createElement('style');s.textContent=`
.radian-menu-btn{border:1px solid #ead3d5;background:#fff7f7;color:#8f1118;border-radius:9px;min-height:36px;padding:5px 10px;font-size:20px;font-weight:900;flex:0 0 46px}.radian-drawer-backdrop{position:fixed;inset:0;z-index:500;background:rgba(0,0,0,.45);display:none}.radian-drawer-backdrop.open{display:block}.radian-drawer{position:absolute;top:0;right:0;width:min(86vw,340px);height:100%;background:#fff;box-shadow:-8px 0 28px rgba(0,0,0,.18);padding:18px;overflow:auto}.radian-drawer-head{text-align:center;border-bottom:1px solid #eee;padding-bottom:14px;margin-bottom:12px}.radian-drawer-head img{width:110px;height:110px;object-fit:contain}.radian-drawer-head b{display:block;font-size:18px;margin-top:6px}.radian-menu-item{width:100%;min-height:48px;margin:6px 0;border:1px solid #e4e7ec;background:#fff;border-radius:12px;text-align:right;padding:8px 12px;font-weight:900;color:#344054}.radian-menu-item.primary{background:#b80f16;color:#fff;border-color:#b80f16}.radian-about{font-size:12px;line-height:1.9;color:#667085;background:#f8fafc;border-radius:12px;padding:12px;margin-top:10px;text-align:right}.chrome-prompt{position:fixed;inset:0;z-index:900;background:#fff;display:none;align-items:center;justify-content:center;padding:22px}.chrome-prompt.open{display:flex}.chrome-card{width:min(100%,420px);text-align:center}.chrome-card img{width:170px;height:170px;object-fit:contain;margin-bottom:10px}.chrome-card h2{font-size:21px;margin:6px 0}.chrome-card p{color:#667085;font-size:13px;line-height:1.9}.chrome-open{width:100%;min-height:56px;border:0;border-radius:15px;background:#b80f16;color:#fff;font-size:16px;font-weight:900;margin-top:14px}.chrome-open:disabled{opacity:.55}.chrome-stay{width:100%;min-height:48px;border:1px solid #d0d5dd;border-radius:13px;background:#fff;color:#344054;font-weight:800;margin-top:8px}`;document.head.appendChild(s)}
function buildMenu(){const tools=document.querySelector('.quick-tools');if(!tools)return;const oldInstall=byId('installPwa'),oldExit=byId('goWelcome');if(oldInstall)oldInstall.style.display='none';if(oldExit)oldExit.style.display='none';const btn=document.createElement('button');btn.className='radian-menu-btn';btn.type='button';btn.setAttribute('aria-label','منوی برنامه');btn.textContent='☰';tools.prepend(btn);const back=document.createElement('div');back.className='radian-drawer-backdrop';back.innerHTML=`<aside class="radian-drawer"><div class="radian-drawer-head"><img src="logo.png?v=3404" alt="لوگوی رادیان"><b>رادیان پارت آریا</b><small>لیست قیمت و ثبت سفارش مشتری</small></div><button class="radian-menu-item primary" id="drawerInstall">نصب برنامه روی گوشی</button>${isAndroid()?'<button class="radian-menu-item" id="drawerChrome">باز کردن در Chrome</button>':''}<button class="radian-menu-item" id="drawerAbout">درباره ما</button><button class="radian-menu-item" id="drawerHome">صفحه اول رادیان</button><button class="radian-menu-item" id="drawerExit">خروج</button><div class="radian-about" id="aboutBox" hidden><b>درباره رادیان پارت آریا</b><br>سامانه مشاهده لیست قیمت و ثبت سفارش مشتریان رادیان پارت آریا.<br>نسخه برنامه: 3.4.0</div></aside>`;document.body.appendChild(back);const close=()=>back.classList.remove('open');btn.onclick=()=>back.classList.add('open');back.addEventListener('click',e=>{if(e.target===back)close()});byId('drawerInstall').onclick=()=>{close();setTimeout(installRadian,80)};byId('drawerChrome')&&(byId('drawerChrome').onclick=()=>{close();openInChrome()});byId('drawerAbout').onclick=()=>{const a=byId('aboutBox');a.hidden=!a.hidden};byId('drawerHome').onclick=()=>{close();welcome()};byId('drawerExit').onclick=()=>{close();if(installed()){try{window.close()}catch(e){}setTimeout(welcome,100)}else welcome()}}
function maybePromptChrome(){if(installed()||!isInAppBrowser())return;let p=byId('chromePrompt');if(p)return;p=document.createElement('div');p.className='chrome-prompt open';p.id='chromePrompt';p.innerHTML=`<div class="chrome-card"><img src="logo.png?v=3404" alt="لوگوی رادیان"><h2>رادیان پارت آریا</h2><p>برای نصب راحت و اجرای کامل برنامه، این صفحه را در <b>Google Chrome</b> باز کنید.</p><button id="openChromeNow" class="chrome-open">باز کردن در Chrome</button><button id="stayHere" class="chrome-stay">ادامه در همین مرورگر</button></div>`;document.body.appendChild(p);byId('openChromeNow').onclick=openInChrome;byId('stayHere').onclick=()=>p.remove()}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();radianInstallPrompt=e;installLabels()});
addEventListener('appinstalled',()=>{radianInstallPrompt=null;installLabels();closeInstallPanel()});
byId('installPwa')?.addEventListener('click',installRadian);byId('installWelcome')?.addEventListener('click',installRadian);byId('goWelcome')?.addEventListener('click',welcome);
if('serviceWorker' in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=3404').then(r=>r.update()).catch(()=>{}));
addRuntimeStyles();buildMenu();installLabels();setTimeout(maybePromptChrome,250);
